apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: app
    image: html:make_scratch
    ports:
      - containerPort: 8080
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
    imagePullPolicy: Never
  terminationGracePeriodSeconds: 0
    
---
kind: Service 
apiVersion: v1
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  type: NodePort
  selector:
    name: myapp
  ports:
  - name: tcp
    port: 8080
    targetPort: 8080
    nodePort: 30047
