#apiVersion: v1
#kind: Namespace
#metadata:
#  name: mynamespace
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-example
  labels: 
    app: html-example
spec:
  selector:
    matchLabels:
      label: mytag
  replicas: 1
  template:
    metadata:
      labels:
        label: mytag
    spec:
      containers:  
      - name: my-server2
        image: html_image:v1
---
apiVersion: v1
kind: Service
metadata:
  name: checkbalance
#  namespace: mynamespace
spec:
  type: NodePort
  selector:
    label: mytag
  ports:
  - port: 8080
    name: myport
    targetPort: 8080
    nodePort: 30004
