apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: voter
    type: "roost-example"
  name: voter
spec: 
  type: NodePort
  selector: 
    app: voter
    type: "roost-example"
  ports:
  - name: voter
    port: 80
    targetPort: 3000
    nodePort: 30010

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voter
      type: "roost-example"
  template:
    metadata:
      labels:
        app: voter
        type: "roost-example"
    spec:
      containers:
      - name: voter
        image: voter:latest
<<<<<<< HEAD
        env:
        - name: REACT_APP_BALLOT_ENDPOINT
          value: ballot:80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 
=======
        stdin: true
        tty: true
        env:
        - name: REACT_APP_BALLOT_ENDPOINT
          value: ballot:80
        ports:
        - containerPort: 3000
>>>>>>> 3e799b284840b1a398bf13b2b8b9cc8f83f5e8b2
        imagePullPolicy: Never