apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: voter
    type: "roost-example"
  name: voter
spec: 
  type: NodePort
  selector: 
    app: voter
    type: "roost-example"
  ports:
  - name: voter
    port: 90
    targetPort: 81
    nodePort: 30030
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voter
      type: "roost-example"
  template:
    metadata:
      labels:
        app: voter
        type: "roost-example"
    spec:
      containers:
      - name: voter
        image: voter:latest
        env:
        - name: REACT_APP_BALLOT_ENDPOINT
          value: ballot:80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 
        imagePullPolicy: Never