apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: voter
    type: "roost-example"
  name: voter
spec: 
  type: NodePort
  selector: 
    app: voter
    type: "roost-example"
  ports:
  - name: voter
    port: 80
    targetPort: 3000
    nodePort: 30010

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: voter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voter
      type: "roost-example"
  template:
    metadata:
      labels:
        app: voter
        type: "roost-example"
    spec:
      containers:
      - name: voter
        image: voter:latest
        stdin: true
        tty: true
        env:
        - name: REACT_APP_BALLOT_ENDPOINT
          value: ballot:80
        ports:
        - containerPort: 3000
        imagePullPolicy: Never