apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: node-reader
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing nodes
  # objects is "nodes"
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]