apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-consumer
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: service-1-consumer
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: event-display
          # Source code: https://github.com/knative/eventing-contrib/blob/release-0.6/cmd/event_display/main.go
          image: gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display@sha256:37ace92b63fc516ad4c8331b6b3b2d84e4ab2d8ba898e387c0b6f68f0e3081c4

---
# Service pointing at the previous Deployment. This will be the target for event consumption.
kind: Service
apiVersion: v1
metadata:
  name: service-1-consumer
spec:
  selector:
    app: service-1-consumer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: service-1-consumer
spec:
  filter:
    attributes:
      # type: newMessage
      source: service
  subscriber:
    ref:
     apiVersion: v1
     kind: Service
     name: service-1-consumer
