apiVersion: v1
kind: Pod
metadata:
  name: busyhost
spec:
  containers:
  - image: busybox
    name: test-container
    command:["sleep","3600"]    
    volumeMounts:
    - mountPath: /host
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /june
