apiVersion: batch/v1beta1
kind: CronJob # suitable for periodic jobs
metadata:
  name: cron-job
  labels:
    owner: zbio
spec:
  schedule: "*/1 * * * *" # creates a job every minute, accepts standard cron schedule format
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the ZKE cluster
          restartPolicy: OnFailure
