apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30020
    targetPort: 83
    name: result-service
  selector:
    app: result
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  labels:
    app: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: result:latest
        env:
        - name: BALLOT_ENDPOINT 
          value: ballot:80
        ports:
        - containerPort: 83
          name: result
        imagePullPolicy: Never
          
