apiVersion: v1
kind: Service
metadata: 
  labels: 
    apps: ballot
  name: ballot
spec: 
  type: ClusterIP
  selector: 
    app: ballot
  ports:
  - name: ballot
    port: 80
    targetPort: 82

--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: ballot
  name: ballot
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: ballot
  template: 
    metadata: 
      labels: 
        app: ballot
    spec: 
      containers: 
      - image: ballot:latest
        name: ballot
        ports:
        - containerPort: 82
        imagePullPolicy: Never