apiVersion: v1
kind: PersistentVolume
metadata:
  name: kaniko-cache-volume
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - "ReadOnlyMany"
  hostPath:
    path: /tmp/kaniko-cache
    type: DirectoryOrCreate
